referenceDocs:
  showConsole: true
  # Limits number of languages in sample bar, rest get pushed to menu
  samplesTabsMaxCount: 3
  # Enhances readability since we have longer endpoints
  pathInMiddlePanel: true
  # Sets docs to generate a unique page per endpoint. Important for SEO
  pagination: item
  # Helps surface the parameters users care about most
  requiredPropsFirst: true
  # Allows search to index nested references (like event payloads)
  searchMaxDepth: 4
  # Boosts search for terms found in endpoint titles
  searchOperationTitleBoost: 5

  # Looking for something nested? Turn on the settings below and find in page
  # pagination: none
  # ctrlFHijack: false
  # schemaExpansionLevel: all
