/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// BulkSendJobGetResponseSignatureRequestsAllOf struct for BulkSendJobGetResponseSignatureRequestsAllOf
type BulkSendJobGetResponseSignatureRequestsAllOf struct {
	// The id of the BulkSendJob.
	BulkSendJobId *string `json:"bulk_send_job_id,omitempty"`
}

// NewBulkSendJobGetResponseSignatureRequestsAllOf instantiates a new BulkSendJobGetResponseSignatureRequestsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkSendJobGetResponseSignatureRequestsAllOf() *BulkSendJobGetResponseSignatureRequestsAllOf {
	this := BulkSendJobGetResponseSignatureRequestsAllOf{}
	return &this
}

// NewBulkSendJobGetResponseSignatureRequestsAllOfWithDefaults instantiates a new BulkSendJobGetResponseSignatureRequestsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkSendJobGetResponseSignatureRequestsAllOfWithDefaults() *BulkSendJobGetResponseSignatureRequestsAllOf {
	this := BulkSendJobGetResponseSignatureRequestsAllOf{}
	return &this
}

// GetBulkSendJobId returns the BulkSendJobId field value if set, zero value otherwise.
func (o *BulkSendJobGetResponseSignatureRequestsAllOf) GetBulkSendJobId() string {
	if o == nil || o.BulkSendJobId == nil {
		var ret string
		return ret
	}
	return *o.BulkSendJobId
}

// GetBulkSendJobIdOk returns a tuple with the BulkSendJobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendJobGetResponseSignatureRequestsAllOf) GetBulkSendJobIdOk() (*string, bool) {
	if o == nil || o.BulkSendJobId == nil {
		return nil, false
	}
	return o.BulkSendJobId, true
}

// HasBulkSendJobId returns a boolean if a field has been set.
func (o *BulkSendJobGetResponseSignatureRequestsAllOf) HasBulkSendJobId() bool {
	if o != nil && o.BulkSendJobId != nil {
		return true
	}

	return false
}

// SetBulkSendJobId gets a reference to the given string and assigns it to the BulkSendJobId field.
func (o *BulkSendJobGetResponseSignatureRequestsAllOf) SetBulkSendJobId(v string) {
	o.BulkSendJobId = &v
}

func (o BulkSendJobGetResponseSignatureRequestsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BulkSendJobId != nil {
		toSerialize["bulk_send_job_id"] = o.BulkSendJobId
	}
	return json.Marshal(toSerialize)
}

type NullableBulkSendJobGetResponseSignatureRequestsAllOf struct {
	value *BulkSendJobGetResponseSignatureRequestsAllOf
	isSet bool
}

func (v NullableBulkSendJobGetResponseSignatureRequestsAllOf) Get() *BulkSendJobGetResponseSignatureRequestsAllOf {
	return v.value
}

func (v *NullableBulkSendJobGetResponseSignatureRequestsAllOf) Set(val *BulkSendJobGetResponseSignatureRequestsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkSendJobGetResponseSignatureRequestsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkSendJobGetResponseSignatureRequestsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkSendJobGetResponseSignatureRequestsAllOf(val *BulkSendJobGetResponseSignatureRequestsAllOf) *NullableBulkSendJobGetResponseSignatureRequestsAllOf {
	return &NullableBulkSendJobGetResponseSignatureRequestsAllOf{value: val, isSet: true}
}

func (v NullableBulkSendJobGetResponseSignatureRequestsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkSendJobGetResponseSignatureRequestsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


