/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// TemplateResponseDocumentStaticFieldTextAllOf struct for TemplateResponseDocumentStaticFieldTextAllOf
type TemplateResponseDocumentStaticFieldTextAllOf struct {
	// The type of this static field. See [field types](/api/reference/constants/#field-types).  * Text Field uses `TemplateResponseDocumentStaticFieldText` * Dropdown Field uses `TemplateResponseDocumentStaticFieldDropdown` * Hyperlink Field uses `TemplateResponseDocumentStaticFieldHyperlink` * Checkbox Field uses `TemplateResponseDocumentStaticFieldCheckbox` * Radio Field uses `TemplateResponseDocumentStaticFieldRadio` * Signature Field uses `TemplateResponseDocumentStaticFieldSignature` * Date Signed Field uses `TemplateResponseDocumentStaticFieldDateSigned` * Initials Field uses `TemplateResponseDocumentStaticFieldInitials`
	Type *string `json:"type,omitempty"`
}

// NewTemplateResponseDocumentStaticFieldTextAllOf instantiates a new TemplateResponseDocumentStaticFieldTextAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponseDocumentStaticFieldTextAllOf() *TemplateResponseDocumentStaticFieldTextAllOf {
	this := TemplateResponseDocumentStaticFieldTextAllOf{}
	var type_ string = "text"
	this.Type = &type_
	return &this
}

// NewTemplateResponseDocumentStaticFieldTextAllOfWithDefaults instantiates a new TemplateResponseDocumentStaticFieldTextAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseDocumentStaticFieldTextAllOfWithDefaults() *TemplateResponseDocumentStaticFieldTextAllOf {
	this := TemplateResponseDocumentStaticFieldTextAllOf{}
	var type_ string = "text"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TemplateResponseDocumentStaticFieldTextAllOf) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentStaticFieldTextAllOf) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TemplateResponseDocumentStaticFieldTextAllOf) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TemplateResponseDocumentStaticFieldTextAllOf) SetType(v string) {
	o.Type = &v
}

func (o TemplateResponseDocumentStaticFieldTextAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateResponseDocumentStaticFieldTextAllOf struct {
	value *TemplateResponseDocumentStaticFieldTextAllOf
	isSet bool
}

func (v NullableTemplateResponseDocumentStaticFieldTextAllOf) Get() *TemplateResponseDocumentStaticFieldTextAllOf {
	return v.value
}

func (v *NullableTemplateResponseDocumentStaticFieldTextAllOf) Set(val *TemplateResponseDocumentStaticFieldTextAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponseDocumentStaticFieldTextAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponseDocumentStaticFieldTextAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponseDocumentStaticFieldTextAllOf(val *TemplateResponseDocumentStaticFieldTextAllOf) *NullableTemplateResponseDocumentStaticFieldTextAllOf {
	return &NullableTemplateResponseDocumentStaticFieldTextAllOf{value: val, isSet: true}
}

func (v NullableTemplateResponseDocumentStaticFieldTextAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponseDocumentStaticFieldTextAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


