/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// EmbeddedEditUrlResponse struct for EmbeddedEditUrlResponse
type EmbeddedEditUrlResponse struct {
	Embedded *EmbeddedEditUrlResponseEmbedded `json:"embedded,omitempty"`
	// A list of warnings.
	Warnings *[]WarningResponse `json:"warnings,omitempty"`
}

// NewEmbeddedEditUrlResponse instantiates a new EmbeddedEditUrlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedEditUrlResponse() *EmbeddedEditUrlResponse {
	this := EmbeddedEditUrlResponse{}
	return &this
}

// NewEmbeddedEditUrlResponseWithDefaults instantiates a new EmbeddedEditUrlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedEditUrlResponseWithDefaults() *EmbeddedEditUrlResponse {
	this := EmbeddedEditUrlResponse{}
	return &this
}

// GetEmbedded returns the Embedded field value if set, zero value otherwise.
func (o *EmbeddedEditUrlResponse) GetEmbedded() EmbeddedEditUrlResponseEmbedded {
	if o == nil || o.Embedded == nil {
		var ret EmbeddedEditUrlResponseEmbedded
		return ret
	}
	return *o.Embedded
}

// GetEmbeddedOk returns a tuple with the Embedded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedEditUrlResponse) GetEmbeddedOk() (*EmbeddedEditUrlResponseEmbedded, bool) {
	if o == nil || o.Embedded == nil {
		return nil, false
	}
	return o.Embedded, true
}

// HasEmbedded returns a boolean if a field has been set.
func (o *EmbeddedEditUrlResponse) HasEmbedded() bool {
	if o != nil && o.Embedded != nil {
		return true
	}

	return false
}

// SetEmbedded gets a reference to the given EmbeddedEditUrlResponseEmbedded and assigns it to the Embedded field.
func (o *EmbeddedEditUrlResponse) SetEmbedded(v EmbeddedEditUrlResponseEmbedded) {
	o.Embedded = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *EmbeddedEditUrlResponse) GetWarnings() []WarningResponse {
	if o == nil || o.Warnings == nil {
		var ret []WarningResponse
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedEditUrlResponse) GetWarningsOk() (*[]WarningResponse, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *EmbeddedEditUrlResponse) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []WarningResponse and assigns it to the Warnings field.
func (o *EmbeddedEditUrlResponse) SetWarnings(v []WarningResponse) {
	o.Warnings = &v
}

func (o EmbeddedEditUrlResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Embedded != nil {
		toSerialize["embedded"] = o.Embedded
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableEmbeddedEditUrlResponse struct {
	value *EmbeddedEditUrlResponse
	isSet bool
}

func (v NullableEmbeddedEditUrlResponse) Get() *EmbeddedEditUrlResponse {
	return v.value
}

func (v *NullableEmbeddedEditUrlResponse) Set(val *EmbeddedEditUrlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedEditUrlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedEditUrlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedEditUrlResponse(val *EmbeddedEditUrlResponse) *NullableEmbeddedEditUrlResponse {
	return &NullableEmbeddedEditUrlResponse{value: val, isSet: true}
}

func (v NullableEmbeddedEditUrlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedEditUrlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


