/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// SignatureRequestResponseDataValueDateSignedAllOf struct for SignatureRequestResponseDataValueDateSignedAllOf
type SignatureRequestResponseDataValueDateSignedAllOf struct {
	// A date
	Type *string `json:"type,omitempty"`
	// The value of the form field.
	Value *string `json:"value,omitempty"`
}

// NewSignatureRequestResponseDataValueDateSignedAllOf instantiates a new SignatureRequestResponseDataValueDateSignedAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignatureRequestResponseDataValueDateSignedAllOf() *SignatureRequestResponseDataValueDateSignedAllOf {
	this := SignatureRequestResponseDataValueDateSignedAllOf{}
	var type_ string = "date_signed"
	this.Type = &type_
	return &this
}

// NewSignatureRequestResponseDataValueDateSignedAllOfWithDefaults instantiates a new SignatureRequestResponseDataValueDateSignedAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignatureRequestResponseDataValueDateSignedAllOfWithDefaults() *SignatureRequestResponseDataValueDateSignedAllOf {
	this := SignatureRequestResponseDataValueDateSignedAllOf{}
	var type_ string = "date_signed"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SignatureRequestResponseDataValueDateSignedAllOf) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignatureRequestResponseDataValueDateSignedAllOf) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SignatureRequestResponseDataValueDateSignedAllOf) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SignatureRequestResponseDataValueDateSignedAllOf) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SignatureRequestResponseDataValueDateSignedAllOf) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignatureRequestResponseDataValueDateSignedAllOf) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SignatureRequestResponseDataValueDateSignedAllOf) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *SignatureRequestResponseDataValueDateSignedAllOf) SetValue(v string) {
	o.Value = &v
}

func (o SignatureRequestResponseDataValueDateSignedAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableSignatureRequestResponseDataValueDateSignedAllOf struct {
	value *SignatureRequestResponseDataValueDateSignedAllOf
	isSet bool
}

func (v NullableSignatureRequestResponseDataValueDateSignedAllOf) Get() *SignatureRequestResponseDataValueDateSignedAllOf {
	return v.value
}

func (v *NullableSignatureRequestResponseDataValueDateSignedAllOf) Set(val *SignatureRequestResponseDataValueDateSignedAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSignatureRequestResponseDataValueDateSignedAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSignatureRequestResponseDataValueDateSignedAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignatureRequestResponseDataValueDateSignedAllOf(val *SignatureRequestResponseDataValueDateSignedAllOf) *NullableSignatureRequestResponseDataValueDateSignedAllOf {
	return &NullableSignatureRequestResponseDataValueDateSignedAllOf{value: val, isSet: true}
}

func (v NullableSignatureRequestResponseDataValueDateSignedAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignatureRequestResponseDataValueDateSignedAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


