/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// TemplateResponseCCRole struct for TemplateResponseCCRole
type TemplateResponseCCRole struct {
	// The name of the Role.
	Name *string `json:"name,omitempty"`
}

// NewTemplateResponseCCRole instantiates a new TemplateResponseCCRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponseCCRole() *TemplateResponseCCRole {
	this := TemplateResponseCCRole{}
	return &this
}

// NewTemplateResponseCCRoleWithDefaults instantiates a new TemplateResponseCCRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseCCRoleWithDefaults() *TemplateResponseCCRole {
	this := TemplateResponseCCRole{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TemplateResponseCCRole) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseCCRole) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TemplateResponseCCRole) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TemplateResponseCCRole) SetName(v string) {
	o.Name = &v
}

func (o TemplateResponseCCRole) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateResponseCCRole struct {
	value *TemplateResponseCCRole
	isSet bool
}

func (v NullableTemplateResponseCCRole) Get() *TemplateResponseCCRole {
	return v.value
}

func (v *NullableTemplateResponseCCRole) Set(val *TemplateResponseCCRole) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponseCCRole) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponseCCRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponseCCRole(val *TemplateResponseCCRole) *NullableTemplateResponseCCRole {
	return &NullableTemplateResponseCCRole{value: val, isSet: true}
}

func (v NullableTemplateResponseCCRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponseCCRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


