/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// SignatureRequestResponseDataValueCheckbox struct for SignatureRequestResponseDataValueCheckbox
type SignatureRequestResponseDataValueCheckbox struct {
	// A yes/no checkbox
	Type *string `json:"type,omitempty"`
	// The value of the form field.
	Value *bool `json:"value,omitempty"`
}

// NewSignatureRequestResponseDataValueCheckbox instantiates a new SignatureRequestResponseDataValueCheckbox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignatureRequestResponseDataValueCheckbox() *SignatureRequestResponseDataValueCheckbox {
	this := SignatureRequestResponseDataValueCheckbox{}
	var type_ string = "checkbox"
	this.Type = &type_
	return &this
}

// NewSignatureRequestResponseDataValueCheckboxWithDefaults instantiates a new SignatureRequestResponseDataValueCheckbox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignatureRequestResponseDataValueCheckboxWithDefaults() *SignatureRequestResponseDataValueCheckbox {
	this := SignatureRequestResponseDataValueCheckbox{}
	var type_ string = "checkbox"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SignatureRequestResponseDataValueCheckbox) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignatureRequestResponseDataValueCheckbox) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SignatureRequestResponseDataValueCheckbox) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SignatureRequestResponseDataValueCheckbox) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SignatureRequestResponseDataValueCheckbox) GetValue() bool {
	if o == nil || o.Value == nil {
		var ret bool
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignatureRequestResponseDataValueCheckbox) GetValueOk() (*bool, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SignatureRequestResponseDataValueCheckbox) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given bool and assigns it to the Value field.
func (o *SignatureRequestResponseDataValueCheckbox) SetValue(v bool) {
	o.Value = &v
}

func (o SignatureRequestResponseDataValueCheckbox) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableSignatureRequestResponseDataValueCheckbox struct {
	value *SignatureRequestResponseDataValueCheckbox
	isSet bool
}

func (v NullableSignatureRequestResponseDataValueCheckbox) Get() *SignatureRequestResponseDataValueCheckbox {
	return v.value
}

func (v *NullableSignatureRequestResponseDataValueCheckbox) Set(val *SignatureRequestResponseDataValueCheckbox) {
	v.value = val
	v.isSet = true
}

func (v NullableSignatureRequestResponseDataValueCheckbox) IsSet() bool {
	return v.isSet
}

func (v *NullableSignatureRequestResponseDataValueCheckbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignatureRequestResponseDataValueCheckbox(val *SignatureRequestResponseDataValueCheckbox) *NullableSignatureRequestResponseDataValueCheckbox {
	return &NullableSignatureRequestResponseDataValueCheckbox{value: val, isSet: true}
}

func (v NullableSignatureRequestResponseDataValueCheckbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignatureRequestResponseDataValueCheckbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


