/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// TemplateResponseDocumentFormFieldBase An array of Form Field objects containing the name and type of each named field.
type TemplateResponseDocumentFormFieldBase struct {
	Type string `json:"type"`
	// A unique id for the form field.
	ApiId *string `json:"api_id,omitempty"`
	// The name of the form field.
	Name *string `json:"name,omitempty"`
	// The signer of the Form Field.
	Signer *string `json:"signer,omitempty"`
	// The horizontal offset in pixels for this form field.
	X *int32 `json:"x,omitempty"`
	// The vertical offset in pixels for this form field.
	Y *int32 `json:"y,omitempty"`
	// The width in pixels of this form field.
	Width *int32 `json:"width,omitempty"`
	// The height in pixels of this form field.
	Height *int32 `json:"height,omitempty"`
	// Boolean showing whether or not this field is required.
	Required *bool `json:"required,omitempty"`
	// The name of the group this field is in. If this field is not a group, this defaults to `null` except for Radio fields.
	Group NullableString `json:"group,omitempty"`
}

// NewTemplateResponseDocumentFormFieldBase instantiates a new TemplateResponseDocumentFormFieldBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponseDocumentFormFieldBase(type_ string) *TemplateResponseDocumentFormFieldBase {
	this := TemplateResponseDocumentFormFieldBase{}
	this.Type = type_
	return &this
}

// NewTemplateResponseDocumentFormFieldBaseWithDefaults instantiates a new TemplateResponseDocumentFormFieldBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseDocumentFormFieldBaseWithDefaults() *TemplateResponseDocumentFormFieldBase {
	this := TemplateResponseDocumentFormFieldBase{}
	return &this
}

// GetType returns the Type field value
func (o *TemplateResponseDocumentFormFieldBase) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldBase) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TemplateResponseDocumentFormFieldBase) SetType(v string) {
	o.Type = v
}

// GetApiId returns the ApiId field value if set, zero value otherwise.
func (o *TemplateResponseDocumentFormFieldBase) GetApiId() string {
	if o == nil || o.ApiId == nil {
		var ret string
		return ret
	}
	return *o.ApiId
}

// GetApiIdOk returns a tuple with the ApiId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldBase) GetApiIdOk() (*string, bool) {
	if o == nil || o.ApiId == nil {
		return nil, false
	}
	return o.ApiId, true
}

// HasApiId returns a boolean if a field has been set.
func (o *TemplateResponseDocumentFormFieldBase) HasApiId() bool {
	if o != nil && o.ApiId != nil {
		return true
	}

	return false
}

// SetApiId gets a reference to the given string and assigns it to the ApiId field.
func (o *TemplateResponseDocumentFormFieldBase) SetApiId(v string) {
	o.ApiId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TemplateResponseDocumentFormFieldBase) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldBase) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TemplateResponseDocumentFormFieldBase) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TemplateResponseDocumentFormFieldBase) SetName(v string) {
	o.Name = &v
}

// GetSigner returns the Signer field value if set, zero value otherwise.
func (o *TemplateResponseDocumentFormFieldBase) GetSigner() string {
	if o == nil || o.Signer == nil {
		var ret string
		return ret
	}
	return *o.Signer
}

// GetSignerOk returns a tuple with the Signer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldBase) GetSignerOk() (*string, bool) {
	if o == nil || o.Signer == nil {
		return nil, false
	}
	return o.Signer, true
}

// HasSigner returns a boolean if a field has been set.
func (o *TemplateResponseDocumentFormFieldBase) HasSigner() bool {
	if o != nil && o.Signer != nil {
		return true
	}

	return false
}

// SetSigner gets a reference to the given string and assigns it to the Signer field.
func (o *TemplateResponseDocumentFormFieldBase) SetSigner(v string) {
	o.Signer = &v
}

// GetX returns the X field value if set, zero value otherwise.
func (o *TemplateResponseDocumentFormFieldBase) GetX() int32 {
	if o == nil || o.X == nil {
		var ret int32
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldBase) GetXOk() (*int32, bool) {
	if o == nil || o.X == nil {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *TemplateResponseDocumentFormFieldBase) HasX() bool {
	if o != nil && o.X != nil {
		return true
	}

	return false
}

// SetX gets a reference to the given int32 and assigns it to the X field.
func (o *TemplateResponseDocumentFormFieldBase) SetX(v int32) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *TemplateResponseDocumentFormFieldBase) GetY() int32 {
	if o == nil || o.Y == nil {
		var ret int32
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldBase) GetYOk() (*int32, bool) {
	if o == nil || o.Y == nil {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *TemplateResponseDocumentFormFieldBase) HasY() bool {
	if o != nil && o.Y != nil {
		return true
	}

	return false
}

// SetY gets a reference to the given int32 and assigns it to the Y field.
func (o *TemplateResponseDocumentFormFieldBase) SetY(v int32) {
	o.Y = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *TemplateResponseDocumentFormFieldBase) GetWidth() int32 {
	if o == nil || o.Width == nil {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldBase) GetWidthOk() (*int32, bool) {
	if o == nil || o.Width == nil {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *TemplateResponseDocumentFormFieldBase) HasWidth() bool {
	if o != nil && o.Width != nil {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *TemplateResponseDocumentFormFieldBase) SetWidth(v int32) {
	o.Width = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *TemplateResponseDocumentFormFieldBase) GetHeight() int32 {
	if o == nil || o.Height == nil {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldBase) GetHeightOk() (*int32, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *TemplateResponseDocumentFormFieldBase) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *TemplateResponseDocumentFormFieldBase) SetHeight(v int32) {
	o.Height = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *TemplateResponseDocumentFormFieldBase) GetRequired() bool {
	if o == nil || o.Required == nil {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldBase) GetRequiredOk() (*bool, bool) {
	if o == nil || o.Required == nil {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *TemplateResponseDocumentFormFieldBase) HasRequired() bool {
	if o != nil && o.Required != nil {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *TemplateResponseDocumentFormFieldBase) SetRequired(v bool) {
	o.Required = &v
}

// GetGroup returns the Group field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateResponseDocumentFormFieldBase) GetGroup() string {
	if o == nil || o.Group.Get() == nil {
		var ret string
		return ret
	}
	return *o.Group.Get()
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponseDocumentFormFieldBase) GetGroupOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Group.Get(), o.Group.IsSet()
}

// HasGroup returns a boolean if a field has been set.
func (o *TemplateResponseDocumentFormFieldBase) HasGroup() bool {
	if o != nil && o.Group.IsSet() {
		return true
	}

	return false
}

// SetGroup gets a reference to the given NullableString and assigns it to the Group field.
func (o *TemplateResponseDocumentFormFieldBase) SetGroup(v string) {
	o.Group.Set(&v)
}
// SetGroupNil sets the value for Group to be an explicit nil
func (o *TemplateResponseDocumentFormFieldBase) SetGroupNil() {
	o.Group.Set(nil)
}

// UnsetGroup ensures that no value is present for Group, not even an explicit nil
func (o *TemplateResponseDocumentFormFieldBase) UnsetGroup() {
	o.Group.Unset()
}

func (o TemplateResponseDocumentFormFieldBase) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.ApiId != nil {
		toSerialize["api_id"] = o.ApiId
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Signer != nil {
		toSerialize["signer"] = o.Signer
	}
	if o.X != nil {
		toSerialize["x"] = o.X
	}
	if o.Y != nil {
		toSerialize["y"] = o.Y
	}
	if o.Width != nil {
		toSerialize["width"] = o.Width
	}
	if o.Height != nil {
		toSerialize["height"] = o.Height
	}
	if o.Required != nil {
		toSerialize["required"] = o.Required
	}
	if o.Group.IsSet() {
		toSerialize["group"] = o.Group.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateResponseDocumentFormFieldBase struct {
	value *TemplateResponseDocumentFormFieldBase
	isSet bool
}

func (v NullableTemplateResponseDocumentFormFieldBase) Get() *TemplateResponseDocumentFormFieldBase {
	return v.value
}

func (v *NullableTemplateResponseDocumentFormFieldBase) Set(val *TemplateResponseDocumentFormFieldBase) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponseDocumentFormFieldBase) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponseDocumentFormFieldBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponseDocumentFormFieldBase(val *TemplateResponseDocumentFormFieldBase) *NullableTemplateResponseDocumentFormFieldBase {
	return &NullableTemplateResponseDocumentFormFieldBase{value: val, isSet: true}
}

func (v NullableTemplateResponseDocumentFormFieldBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponseDocumentFormFieldBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


