/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// BulkSendJobGetResponse struct for BulkSendJobGetResponse
type BulkSendJobGetResponse struct {
	BulkSendJob *BulkSendJobResponse `json:"bulk_send_job,omitempty"`
	ListInfo *ListInfoResponse `json:"list_info,omitempty"`
	// Contains information about the Signature Requests sent in bulk.
	SignatureRequests *[]BulkSendJobGetResponseSignatureRequests `json:"signature_requests,omitempty"`
	// A list of warnings.
	Warnings *[]WarningResponse `json:"warnings,omitempty"`
}

// NewBulkSendJobGetResponse instantiates a new BulkSendJobGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkSendJobGetResponse() *BulkSendJobGetResponse {
	this := BulkSendJobGetResponse{}
	return &this
}

// NewBulkSendJobGetResponseWithDefaults instantiates a new BulkSendJobGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkSendJobGetResponseWithDefaults() *BulkSendJobGetResponse {
	this := BulkSendJobGetResponse{}
	return &this
}

// GetBulkSendJob returns the BulkSendJob field value if set, zero value otherwise.
func (o *BulkSendJobGetResponse) GetBulkSendJob() BulkSendJobResponse {
	if o == nil || o.BulkSendJob == nil {
		var ret BulkSendJobResponse
		return ret
	}
	return *o.BulkSendJob
}

// GetBulkSendJobOk returns a tuple with the BulkSendJob field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendJobGetResponse) GetBulkSendJobOk() (*BulkSendJobResponse, bool) {
	if o == nil || o.BulkSendJob == nil {
		return nil, false
	}
	return o.BulkSendJob, true
}

// HasBulkSendJob returns a boolean if a field has been set.
func (o *BulkSendJobGetResponse) HasBulkSendJob() bool {
	if o != nil && o.BulkSendJob != nil {
		return true
	}

	return false
}

// SetBulkSendJob gets a reference to the given BulkSendJobResponse and assigns it to the BulkSendJob field.
func (o *BulkSendJobGetResponse) SetBulkSendJob(v BulkSendJobResponse) {
	o.BulkSendJob = &v
}

// GetListInfo returns the ListInfo field value if set, zero value otherwise.
func (o *BulkSendJobGetResponse) GetListInfo() ListInfoResponse {
	if o == nil || o.ListInfo == nil {
		var ret ListInfoResponse
		return ret
	}
	return *o.ListInfo
}

// GetListInfoOk returns a tuple with the ListInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendJobGetResponse) GetListInfoOk() (*ListInfoResponse, bool) {
	if o == nil || o.ListInfo == nil {
		return nil, false
	}
	return o.ListInfo, true
}

// HasListInfo returns a boolean if a field has been set.
func (o *BulkSendJobGetResponse) HasListInfo() bool {
	if o != nil && o.ListInfo != nil {
		return true
	}

	return false
}

// SetListInfo gets a reference to the given ListInfoResponse and assigns it to the ListInfo field.
func (o *BulkSendJobGetResponse) SetListInfo(v ListInfoResponse) {
	o.ListInfo = &v
}

// GetSignatureRequests returns the SignatureRequests field value if set, zero value otherwise.
func (o *BulkSendJobGetResponse) GetSignatureRequests() []BulkSendJobGetResponseSignatureRequests {
	if o == nil || o.SignatureRequests == nil {
		var ret []BulkSendJobGetResponseSignatureRequests
		return ret
	}
	return *o.SignatureRequests
}

// GetSignatureRequestsOk returns a tuple with the SignatureRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendJobGetResponse) GetSignatureRequestsOk() (*[]BulkSendJobGetResponseSignatureRequests, bool) {
	if o == nil || o.SignatureRequests == nil {
		return nil, false
	}
	return o.SignatureRequests, true
}

// HasSignatureRequests returns a boolean if a field has been set.
func (o *BulkSendJobGetResponse) HasSignatureRequests() bool {
	if o != nil && o.SignatureRequests != nil {
		return true
	}

	return false
}

// SetSignatureRequests gets a reference to the given []BulkSendJobGetResponseSignatureRequests and assigns it to the SignatureRequests field.
func (o *BulkSendJobGetResponse) SetSignatureRequests(v []BulkSendJobGetResponseSignatureRequests) {
	o.SignatureRequests = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *BulkSendJobGetResponse) GetWarnings() []WarningResponse {
	if o == nil || o.Warnings == nil {
		var ret []WarningResponse
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSendJobGetResponse) GetWarningsOk() (*[]WarningResponse, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *BulkSendJobGetResponse) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []WarningResponse and assigns it to the Warnings field.
func (o *BulkSendJobGetResponse) SetWarnings(v []WarningResponse) {
	o.Warnings = &v
}

func (o BulkSendJobGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BulkSendJob != nil {
		toSerialize["bulk_send_job"] = o.BulkSendJob
	}
	if o.ListInfo != nil {
		toSerialize["list_info"] = o.ListInfo
	}
	if o.SignatureRequests != nil {
		toSerialize["signature_requests"] = o.SignatureRequests
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableBulkSendJobGetResponse struct {
	value *BulkSendJobGetResponse
	isSet bool
}

func (v NullableBulkSendJobGetResponse) Get() *BulkSendJobGetResponse {
	return v.value
}

func (v *NullableBulkSendJobGetResponse) Set(val *BulkSendJobGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkSendJobGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkSendJobGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkSendJobGetResponse(val *BulkSendJobGetResponse) *NullableBulkSendJobGetResponse {
	return &NullableBulkSendJobGetResponse{value: val, isSet: true}
}

func (v NullableBulkSendJobGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkSendJobGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


