/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// TemplateResponseAccount struct for TemplateResponseAccount
type TemplateResponseAccount struct {
	// The id of the Account.
	AccountId *string `json:"account_id,omitempty"`
	// The email address associated with the Account.
	EmailAddress *string `json:"email_address,omitempty"`
	// Returns `true` if the user has been locked out of their account by a team admin.
	IsLocked *bool `json:"is_locked,omitempty"`
	// Returns `true` if the user has a paid Dropbox Sign account.
	IsPaidHs *bool `json:"is_paid_hs,omitempty"`
	// Returns `true` if the user has a paid HelloFax account.
	IsPaidHf *bool `json:"is_paid_hf,omitempty"`
	Quotas *TemplateResponseAccountQuota `json:"quotas,omitempty"`
}

// NewTemplateResponseAccount instantiates a new TemplateResponseAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponseAccount() *TemplateResponseAccount {
	this := TemplateResponseAccount{}
	return &this
}

// NewTemplateResponseAccountWithDefaults instantiates a new TemplateResponseAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseAccountWithDefaults() *TemplateResponseAccount {
	this := TemplateResponseAccount{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *TemplateResponseAccount) GetAccountId() string {
	if o == nil || o.AccountId == nil {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseAccount) GetAccountIdOk() (*string, bool) {
	if o == nil || o.AccountId == nil {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *TemplateResponseAccount) HasAccountId() bool {
	if o != nil && o.AccountId != nil {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *TemplateResponseAccount) SetAccountId(v string) {
	o.AccountId = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *TemplateResponseAccount) GetEmailAddress() string {
	if o == nil || o.EmailAddress == nil {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseAccount) GetEmailAddressOk() (*string, bool) {
	if o == nil || o.EmailAddress == nil {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *TemplateResponseAccount) HasEmailAddress() bool {
	if o != nil && o.EmailAddress != nil {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *TemplateResponseAccount) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

// GetIsLocked returns the IsLocked field value if set, zero value otherwise.
func (o *TemplateResponseAccount) GetIsLocked() bool {
	if o == nil || o.IsLocked == nil {
		var ret bool
		return ret
	}
	return *o.IsLocked
}

// GetIsLockedOk returns a tuple with the IsLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseAccount) GetIsLockedOk() (*bool, bool) {
	if o == nil || o.IsLocked == nil {
		return nil, false
	}
	return o.IsLocked, true
}

// HasIsLocked returns a boolean if a field has been set.
func (o *TemplateResponseAccount) HasIsLocked() bool {
	if o != nil && o.IsLocked != nil {
		return true
	}

	return false
}

// SetIsLocked gets a reference to the given bool and assigns it to the IsLocked field.
func (o *TemplateResponseAccount) SetIsLocked(v bool) {
	o.IsLocked = &v
}

// GetIsPaidHs returns the IsPaidHs field value if set, zero value otherwise.
func (o *TemplateResponseAccount) GetIsPaidHs() bool {
	if o == nil || o.IsPaidHs == nil {
		var ret bool
		return ret
	}
	return *o.IsPaidHs
}

// GetIsPaidHsOk returns a tuple with the IsPaidHs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseAccount) GetIsPaidHsOk() (*bool, bool) {
	if o == nil || o.IsPaidHs == nil {
		return nil, false
	}
	return o.IsPaidHs, true
}

// HasIsPaidHs returns a boolean if a field has been set.
func (o *TemplateResponseAccount) HasIsPaidHs() bool {
	if o != nil && o.IsPaidHs != nil {
		return true
	}

	return false
}

// SetIsPaidHs gets a reference to the given bool and assigns it to the IsPaidHs field.
func (o *TemplateResponseAccount) SetIsPaidHs(v bool) {
	o.IsPaidHs = &v
}

// GetIsPaidHf returns the IsPaidHf field value if set, zero value otherwise.
func (o *TemplateResponseAccount) GetIsPaidHf() bool {
	if o == nil || o.IsPaidHf == nil {
		var ret bool
		return ret
	}
	return *o.IsPaidHf
}

// GetIsPaidHfOk returns a tuple with the IsPaidHf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseAccount) GetIsPaidHfOk() (*bool, bool) {
	if o == nil || o.IsPaidHf == nil {
		return nil, false
	}
	return o.IsPaidHf, true
}

// HasIsPaidHf returns a boolean if a field has been set.
func (o *TemplateResponseAccount) HasIsPaidHf() bool {
	if o != nil && o.IsPaidHf != nil {
		return true
	}

	return false
}

// SetIsPaidHf gets a reference to the given bool and assigns it to the IsPaidHf field.
func (o *TemplateResponseAccount) SetIsPaidHf(v bool) {
	o.IsPaidHf = &v
}

// GetQuotas returns the Quotas field value if set, zero value otherwise.
func (o *TemplateResponseAccount) GetQuotas() TemplateResponseAccountQuota {
	if o == nil || o.Quotas == nil {
		var ret TemplateResponseAccountQuota
		return ret
	}
	return *o.Quotas
}

// GetQuotasOk returns a tuple with the Quotas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseAccount) GetQuotasOk() (*TemplateResponseAccountQuota, bool) {
	if o == nil || o.Quotas == nil {
		return nil, false
	}
	return o.Quotas, true
}

// HasQuotas returns a boolean if a field has been set.
func (o *TemplateResponseAccount) HasQuotas() bool {
	if o != nil && o.Quotas != nil {
		return true
	}

	return false
}

// SetQuotas gets a reference to the given TemplateResponseAccountQuota and assigns it to the Quotas field.
func (o *TemplateResponseAccount) SetQuotas(v TemplateResponseAccountQuota) {
	o.Quotas = &v
}

func (o TemplateResponseAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountId != nil {
		toSerialize["account_id"] = o.AccountId
	}
	if o.EmailAddress != nil {
		toSerialize["email_address"] = o.EmailAddress
	}
	if o.IsLocked != nil {
		toSerialize["is_locked"] = o.IsLocked
	}
	if o.IsPaidHs != nil {
		toSerialize["is_paid_hs"] = o.IsPaidHs
	}
	if o.IsPaidHf != nil {
		toSerialize["is_paid_hf"] = o.IsPaidHf
	}
	if o.Quotas != nil {
		toSerialize["quotas"] = o.Quotas
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateResponseAccount struct {
	value *TemplateResponseAccount
	isSet bool
}

func (v NullableTemplateResponseAccount) Get() *TemplateResponseAccount {
	return v.value
}

func (v *NullableTemplateResponseAccount) Set(val *TemplateResponseAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponseAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponseAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponseAccount(val *TemplateResponseAccount) *NullableTemplateResponseAccount {
	return &NullableTemplateResponseAccount{value: val, isSet: true}
}

func (v NullableTemplateResponseAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponseAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


