/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// SubFormFieldsPerDocumentSignatureAllOf struct for SubFormFieldsPerDocumentSignatureAllOf
type SubFormFieldsPerDocumentSignatureAllOf struct {
	// A signature input field. Use the `SubFormFieldsPerDocumentSignature` class.
	Type string `json:"type"`
}

// NewSubFormFieldsPerDocumentSignatureAllOf instantiates a new SubFormFieldsPerDocumentSignatureAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubFormFieldsPerDocumentSignatureAllOf(type_ string) *SubFormFieldsPerDocumentSignatureAllOf {
	this := SubFormFieldsPerDocumentSignatureAllOf{}
	this.Type = type_
	return &this
}

// NewSubFormFieldsPerDocumentSignatureAllOfWithDefaults instantiates a new SubFormFieldsPerDocumentSignatureAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubFormFieldsPerDocumentSignatureAllOfWithDefaults() *SubFormFieldsPerDocumentSignatureAllOf {
	this := SubFormFieldsPerDocumentSignatureAllOf{}
	var type_ string = "signature"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *SubFormFieldsPerDocumentSignatureAllOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubFormFieldsPerDocumentSignatureAllOf) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubFormFieldsPerDocumentSignatureAllOf) SetType(v string) {
	o.Type = v
}

func (o SubFormFieldsPerDocumentSignatureAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableSubFormFieldsPerDocumentSignatureAllOf struct {
	value *SubFormFieldsPerDocumentSignatureAllOf
	isSet bool
}

func (v NullableSubFormFieldsPerDocumentSignatureAllOf) Get() *SubFormFieldsPerDocumentSignatureAllOf {
	return v.value
}

func (v *NullableSubFormFieldsPerDocumentSignatureAllOf) Set(val *SubFormFieldsPerDocumentSignatureAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSubFormFieldsPerDocumentSignatureAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSubFormFieldsPerDocumentSignatureAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubFormFieldsPerDocumentSignatureAllOf(val *SubFormFieldsPerDocumentSignatureAllOf) *NullableSubFormFieldsPerDocumentSignatureAllOf {
	return &NullableSubFormFieldsPerDocumentSignatureAllOf{value: val, isSet: true}
}

func (v NullableSubFormFieldsPerDocumentSignatureAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubFormFieldsPerDocumentSignatureAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


