/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// TemplateResponseDocumentFormFieldCheckboxAllOf struct for TemplateResponseDocumentFormFieldCheckboxAllOf
type TemplateResponseDocumentFormFieldCheckboxAllOf struct {
	// The type of this form field. See [field types](/api/reference/constants/#field-types).  * Text Field uses `TemplateResponseDocumentFormFieldText` * Dropdown Field uses `TemplateResponseDocumentFormFieldDropdown` * Hyperlink Field uses `TemplateResponseDocumentFormFieldHyperlink` * Checkbox Field uses `TemplateResponseDocumentFormFieldCheckbox` * Radio Field uses `TemplateResponseDocumentFormFieldRadio` * Signature Field uses `TemplateResponseDocumentFormFieldSignature` * Date Signed Field uses `TemplateResponseDocumentFormFieldDateSigned` * Initials Field uses `TemplateResponseDocumentFormFieldInitials`
	Type *string `json:"type,omitempty"`
}

// NewTemplateResponseDocumentFormFieldCheckboxAllOf instantiates a new TemplateResponseDocumentFormFieldCheckboxAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponseDocumentFormFieldCheckboxAllOf() *TemplateResponseDocumentFormFieldCheckboxAllOf {
	this := TemplateResponseDocumentFormFieldCheckboxAllOf{}
	var type_ string = "checkbox"
	this.Type = &type_
	return &this
}

// NewTemplateResponseDocumentFormFieldCheckboxAllOfWithDefaults instantiates a new TemplateResponseDocumentFormFieldCheckboxAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseDocumentFormFieldCheckboxAllOfWithDefaults() *TemplateResponseDocumentFormFieldCheckboxAllOf {
	this := TemplateResponseDocumentFormFieldCheckboxAllOf{}
	var type_ string = "checkbox"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TemplateResponseDocumentFormFieldCheckboxAllOf) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldCheckboxAllOf) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TemplateResponseDocumentFormFieldCheckboxAllOf) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TemplateResponseDocumentFormFieldCheckboxAllOf) SetType(v string) {
	o.Type = &v
}

func (o TemplateResponseDocumentFormFieldCheckboxAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateResponseDocumentFormFieldCheckboxAllOf struct {
	value *TemplateResponseDocumentFormFieldCheckboxAllOf
	isSet bool
}

func (v NullableTemplateResponseDocumentFormFieldCheckboxAllOf) Get() *TemplateResponseDocumentFormFieldCheckboxAllOf {
	return v.value
}

func (v *NullableTemplateResponseDocumentFormFieldCheckboxAllOf) Set(val *TemplateResponseDocumentFormFieldCheckboxAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponseDocumentFormFieldCheckboxAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponseDocumentFormFieldCheckboxAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponseDocumentFormFieldCheckboxAllOf(val *TemplateResponseDocumentFormFieldCheckboxAllOf) *NullableTemplateResponseDocumentFormFieldCheckboxAllOf {
	return &NullableTemplateResponseDocumentFormFieldCheckboxAllOf{value: val, isSet: true}
}

func (v NullableTemplateResponseDocumentFormFieldCheckboxAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponseDocumentFormFieldCheckboxAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


