/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// SubAttachment struct for SubAttachment
type SubAttachment struct {
	// The name of attachment.
	Name string `json:"name"`
	// The signer's index in the `signers` parameter (0-based indexing).  **NOTE**: Only one signer can be assigned per attachment.
	SignerIndex int32 `json:"signer_index"`
	// The instructions for uploading the attachment.
	Instructions *string `json:"instructions,omitempty"`
	// Determines if the attachment must be uploaded.
	Required *bool `json:"required,omitempty"`
}

// NewSubAttachment instantiates a new SubAttachment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubAttachment(name string, signerIndex int32) *SubAttachment {
	this := SubAttachment{}
	this.Name = name
	this.SignerIndex = signerIndex
	var required bool = false
	this.Required = &required
	return &this
}

// NewSubAttachmentWithDefaults instantiates a new SubAttachment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubAttachmentWithDefaults() *SubAttachment {
	this := SubAttachment{}
	var required bool = false
	this.Required = &required
	return &this
}

// GetName returns the Name field value
func (o *SubAttachment) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SubAttachment) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SubAttachment) SetName(v string) {
	o.Name = v
}

// GetSignerIndex returns the SignerIndex field value
func (o *SubAttachment) GetSignerIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SignerIndex
}

// GetSignerIndexOk returns a tuple with the SignerIndex field value
// and a boolean to check if the value has been set.
func (o *SubAttachment) GetSignerIndexOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SignerIndex, true
}

// SetSignerIndex sets field value
func (o *SubAttachment) SetSignerIndex(v int32) {
	o.SignerIndex = v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *SubAttachment) GetInstructions() string {
	if o == nil || o.Instructions == nil {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubAttachment) GetInstructionsOk() (*string, bool) {
	if o == nil || o.Instructions == nil {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *SubAttachment) HasInstructions() bool {
	if o != nil && o.Instructions != nil {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *SubAttachment) SetInstructions(v string) {
	o.Instructions = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *SubAttachment) GetRequired() bool {
	if o == nil || o.Required == nil {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubAttachment) GetRequiredOk() (*bool, bool) {
	if o == nil || o.Required == nil {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *SubAttachment) HasRequired() bool {
	if o != nil && o.Required != nil {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *SubAttachment) SetRequired(v bool) {
	o.Required = &v
}

func (o SubAttachment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["signer_index"] = o.SignerIndex
	}
	if o.Instructions != nil {
		toSerialize["instructions"] = o.Instructions
	}
	if o.Required != nil {
		toSerialize["required"] = o.Required
	}
	return json.Marshal(toSerialize)
}

type NullableSubAttachment struct {
	value *SubAttachment
	isSet bool
}

func (v NullableSubAttachment) Get() *SubAttachment {
	return v.value
}

func (v *NullableSubAttachment) Set(val *SubAttachment) {
	v.value = val
	v.isSet = true
}

func (v NullableSubAttachment) IsSet() bool {
	return v.isSet
}

func (v *NullableSubAttachment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubAttachment(val *SubAttachment) *NullableSubAttachment {
	return &NullableSubAttachment{value: val, isSet: true}
}

func (v NullableSubAttachment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubAttachment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


