/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// TemplateResponseDocumentStaticFieldRadioAllOf struct for TemplateResponseDocumentStaticFieldRadioAllOf
type TemplateResponseDocumentStaticFieldRadioAllOf struct {
	// The type of this static field. See [field types](/api/reference/constants/#field-types).  * Text Field uses `TemplateResponseDocumentStaticFieldText` * Dropdown Field uses `TemplateResponseDocumentStaticFieldDropdown` * Hyperlink Field uses `TemplateResponseDocumentStaticFieldHyperlink` * Checkbox Field uses `TemplateResponseDocumentStaticFieldCheckbox` * Radio Field uses `TemplateResponseDocumentStaticFieldRadio` * Signature Field uses `TemplateResponseDocumentStaticFieldSignature` * Date Signed Field uses `TemplateResponseDocumentStaticFieldDateSigned` * Initials Field uses `TemplateResponseDocumentStaticFieldInitials`
	Type *string `json:"type,omitempty"`
}

// NewTemplateResponseDocumentStaticFieldRadioAllOf instantiates a new TemplateResponseDocumentStaticFieldRadioAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponseDocumentStaticFieldRadioAllOf() *TemplateResponseDocumentStaticFieldRadioAllOf {
	this := TemplateResponseDocumentStaticFieldRadioAllOf{}
	var type_ string = "radio"
	this.Type = &type_
	return &this
}

// NewTemplateResponseDocumentStaticFieldRadioAllOfWithDefaults instantiates a new TemplateResponseDocumentStaticFieldRadioAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseDocumentStaticFieldRadioAllOfWithDefaults() *TemplateResponseDocumentStaticFieldRadioAllOf {
	this := TemplateResponseDocumentStaticFieldRadioAllOf{}
	var type_ string = "radio"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TemplateResponseDocumentStaticFieldRadioAllOf) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentStaticFieldRadioAllOf) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TemplateResponseDocumentStaticFieldRadioAllOf) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TemplateResponseDocumentStaticFieldRadioAllOf) SetType(v string) {
	o.Type = &v
}

func (o TemplateResponseDocumentStaticFieldRadioAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateResponseDocumentStaticFieldRadioAllOf struct {
	value *TemplateResponseDocumentStaticFieldRadioAllOf
	isSet bool
}

func (v NullableTemplateResponseDocumentStaticFieldRadioAllOf) Get() *TemplateResponseDocumentStaticFieldRadioAllOf {
	return v.value
}

func (v *NullableTemplateResponseDocumentStaticFieldRadioAllOf) Set(val *TemplateResponseDocumentStaticFieldRadioAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponseDocumentStaticFieldRadioAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponseDocumentStaticFieldRadioAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponseDocumentStaticFieldRadioAllOf(val *TemplateResponseDocumentStaticFieldRadioAllOf) *NullableTemplateResponseDocumentStaticFieldRadioAllOf {
	return &NullableTemplateResponseDocumentStaticFieldRadioAllOf{value: val, isSet: true}
}

func (v NullableTemplateResponseDocumentStaticFieldRadioAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponseDocumentStaticFieldRadioAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


