/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dropboxsign

import (
	"encoding/json"
)

// SubFormFieldsPerDocumentInitialsAllOf struct for SubFormFieldsPerDocumentInitialsAllOf
type SubFormFieldsPerDocumentInitialsAllOf struct {
	// An input field for initials. Use the `SubFormFieldsPerDocumentInitials` class.
	Type string `json:"type"`
}

// NewSubFormFieldsPerDocumentInitialsAllOf instantiates a new SubFormFieldsPerDocumentInitialsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubFormFieldsPerDocumentInitialsAllOf(type_ string) *SubFormFieldsPerDocumentInitialsAllOf {
	this := SubFormFieldsPerDocumentInitialsAllOf{}
	this.Type = type_
	return &this
}

// NewSubFormFieldsPerDocumentInitialsAllOfWithDefaults instantiates a new SubFormFieldsPerDocumentInitialsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubFormFieldsPerDocumentInitialsAllOfWithDefaults() *SubFormFieldsPerDocumentInitialsAllOf {
	this := SubFormFieldsPerDocumentInitialsAllOf{}
	var type_ string = "initials"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *SubFormFieldsPerDocumentInitialsAllOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubFormFieldsPerDocumentInitialsAllOf) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubFormFieldsPerDocumentInitialsAllOf) SetType(v string) {
	o.Type = v
}

func (o SubFormFieldsPerDocumentInitialsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableSubFormFieldsPerDocumentInitialsAllOf struct {
	value *SubFormFieldsPerDocumentInitialsAllOf
	isSet bool
}

func (v NullableSubFormFieldsPerDocumentInitialsAllOf) Get() *SubFormFieldsPerDocumentInitialsAllOf {
	return v.value
}

func (v *NullableSubFormFieldsPerDocumentInitialsAllOf) Set(val *SubFormFieldsPerDocumentInitialsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSubFormFieldsPerDocumentInitialsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSubFormFieldsPerDocumentInitialsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubFormFieldsPerDocumentInitialsAllOf(val *SubFormFieldsPerDocumentInitialsAllOf) *NullableSubFormFieldsPerDocumentInitialsAllOf {
	return &NullableSubFormFieldsPerDocumentInitialsAllOf{value: val, isSet: true}
}

func (v NullableSubFormFieldsPerDocumentInitialsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubFormFieldsPerDocumentInitialsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


