#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/ef882a4e6c6066007952de3bd7013f9940dc0de7/modules/openapi-generator/src/main/resources/php

set -e

DIR=$(cd `dirname $0` && pwd)
WORKING_DIR="/app/go"

docker run --rm \
  -v "${DIR}/:/local" \
  -v "${DIR}/openapi-sdk.yaml:/local/openapi-sdk.yaml" \
  openapitools/openapi-generator-cli:v5.3.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local"

printf "\nMoving go files to src ...\n"
mkdir -p "${DIR}/src"
find "${DIR}" -maxdepth 1 -name "*.go" -exec mv {} "${DIR}/src/" \;

printf "Replacing strings ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/replace

printf "Scanning for prohibited keywords ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/scan_for

# avoid docker messing with permissions
if [[ -z "$GITHUB_ACTIONS" ]]; then
  chmod 644 "${DIR}/README.md"
  find "${DIR}/docs/" -type f -exec chmod 644 {} \;
  find "${DIR}/examples/" -type f -exec chmod 644 {} \;
  find "${DIR}/test_fixtures/" -type f -exec chmod 644 {} \;
#  find "${DIR}/src/" -type f -exec chmod 644 {} \;
fi

#printf "Running unit tests ...\n"
#bash "${DIR}/bin/php" ./vendor/bin/phpunit
#printf "\n\n"

printf "Success!\n"
